/// <reference types="node" />
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

// The fix ledger's "Remaining work, batched" section plans what is left. This
// keeps the plan and the ledger from drifting apart: every finding still marked
// `open` has to appear in exactly one batch, so a newly opened finding cannot
// quietly land outside the plan, and a batch cannot list an id that does not
// exist. Batch MEMBERSHIP is a judgement call and free to change; the partition
// being complete is not.
const LEDGER = 'docs/deep-code-review-fixes.md'
const repoRoot = join(import.meta.dirname, '..', '..')

function ledger(): string {
  return readFileSync(LEDGER, 'utf8')
}

/** Ids by state, read from the ledger table itself. */
function findingsByState(src: string): Map<string, string> {
  const out = new Map<string, string>()
  const row = /^\| (F\d+) \|(?:[^|]*\|){4} `([a-z-]+)` \|/gm
  for (const m of src.matchAll(row)) out.set(m[1], m[2])
  return out
}

/** Ids listed under each `### n — name` batch heading. */
function batches(src: string): Map<string, string[]> {
  const start = src.indexOf('## Remaining work, batched')
  const end = src.indexOf('## Open leads', start)
  expect(start).toBeGreaterThan(-1)
  const body = src.slice(start, end)
  const out = new Map<string, string[]>()
  const sections = body.split(/^### /m).slice(1)
  for (const sec of sections) {
    const name = sec.split('\n')[0].trim()
    // Only the backticked id run directly under the heading, not prose mentions.
    const idLine = sec.split('\n').find(l => /^(`F\d+`\s*)+$/.test(l.trim()))
    out.set(name, idLine ? [...idLine.matchAll(/F\d+/g)].map(m => m[0]) : [])
  }
  return out
}

describe('the remaining-work plan covers the open findings', () => {
  const src = ledger()
  const state = findingsByState(src)
  const planned = batches(src)
  const allPlanned = [...planned.values()].flat()
  const open = [...state.entries()].filter(([, st]) => st === 'open').map(([id]) => id)

  it('parses both the ledger table and the batch sections', () => {
    expect(state.size).toBeGreaterThan(50)
    expect(planned.size).toBe(7)
    // Not a magic minimum: a closed batch legitimately empties, so the only
    // floor that stays true is "at least enough to cover what is still open".
    expect(allPlanned.length).toBeGreaterThanOrEqual(open.length)
  })

  it('places every open finding in a batch', () => {
    const missing = open.filter(id => !allPlanned.includes(id))
    expect(missing, `open but unplanned: ${missing.join(', ')}`).toEqual([])
  })

  it('places each finding in exactly one batch', () => {
    const dupes = allPlanned.filter((id, i) => allPlanned.indexOf(id) !== i)
    expect([...new Set(dupes)], `listed in more than one batch: ${dupes.join(', ')}`).toEqual([])
  })

  it('lists no finding that does not exist', () => {
    const unknown = allPlanned.filter(id => !state.has(id))
    expect(unknown, `planned but not in the ledger: ${unknown.join(', ')}`).toEqual([])
  })

  it('keeps the batch table counts in step with the sections', () => {
    // `| 2 | Destructive paths | 8 | **2** | ...`
    const rowCounts = [...src.matchAll(/^\| (\d) \| ([^|]+) \| (\d+) \|/gm)]
      .map(m => ({ n: Number(m[1]), count: Number(m[3]) }))
    expect(rowCounts).toHaveLength(7)
    const sizes = [...planned.values()].map(v => v.length)
    expect(rowCounts.map(r => r.count)).toEqual(sizes)
  })
})

describe('the ledger itself stays well formed', () => {
  const src = ledger()

  // The totals are regenerated by script after each batch, and a regex written
  // for the Totals table once matched the States table too and overwrote a state
  // DEFINITION with a count. Both tables use `| \`open\` |` as a row key.
  it('keeps the States table as definitions, not counts', () => {
    const start = src.indexOf('## States')
    const body = src.slice(start, src.indexOf('## Rules', start))
    for (const state of ['open', 'wip', 'fixed', 'fixed-by', 'wontfix', 'blocked']) {
      const row = new RegExp('^\\| `' + state + '` \\| (.*) \\|$', 'm').exec(body)
      expect(row, `no States row for ${state}`).not.toBeNull()
      expect(row![1], `States row for ${state} looks like a count`).not.toMatch(/^\*\*\d+\*\*/)
    }
  })

  // A `fixed` row's evidence names the commit that did the work. Those SHAs are
  // recorded at commit time, so a later rebase of the branch they sit on leaves
  // them pointing at nothing — which is exactly what happened when `gh stack`
  // rebased the batch 4 branch before its PR merged, and the four SHAs written
  // into this file were no longer the ones that reached main. Nothing said so.
  //
  // Skipped on a shallow clone: CI checks out with depth 1, so most of these
  // commits are genuinely absent there and the check would mean nothing.
  it('records commit SHAs that actually exist', () => {
    const shallow = execFileSync('git', ['rev-parse', '--is-shallow-repository'],
      { cwd: repoRoot, encoding: 'utf8' }).trim()
    if (shallow === 'true') return

    const shas = new global.Set(
      [...src.matchAll(/^\| F\d+ \|(?:[^|]*\|){4}\s*`fixed`\s*\|\s*`([0-9a-f]{7,40})`/gm)]
        .map(m => m[1]),
    )
    expect(shas.size).toBeGreaterThan(0)
    // Reachability from HEAD, not mere existence: a rebase leaves the old
    // commits lying around locally, so `cat-file -e` still finds an orphan and
    // reports nothing wrong. What the evidence column claims is that this
    // history contains the fix.
    const unreachable = [...shas].filter(sha => {
      try {
        execFileSync('git', ['merge-base', '--is-ancestor', sha, 'HEAD'], { cwd: repoRoot, stdio: 'ignore' })
        return false
      } catch {
        return true
      }
    })
    expect(unreachable, 'ledger names commits not reachable from HEAD').toEqual([])
  })

  it('reports totals that add up', () => {
    const state = findingsByState(src)
    const totals = src.slice(src.indexOf('## Totals'), src.indexOf('## States'))
    const declared = Number(/\| Findings \| \*\*(\d+)\*\*/.exec(totals)![1])
    expect(declared).toBe(state.size)

    for (const name of ['open', 'fixed', 'fixed-by']) {
      const m = new RegExp('\\| `' + name + '` \\| \\*\\*(\\d+)\\*\\*').exec(totals)
      const actual = [...state.values()].filter(v => v === name).length
      expect(Number(m![1]), `totals row for ${name}`).toBe(actual)
    }
  })
})
